const PRODUCTS = [
  {
    "asin": "B0B61WJRY5",
    "title": "Samsung Lava e Seca WD11M com Digital Inverter WD11M4473PX Inox Look 11/7kg - 220V",
    "image": "https://m.media-amazon.com/images/I/41F+xukODBL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 3599.0,
    "price_original": 0.84,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 508,
    "coupon_code": null,
    "description": "<ul><li>Inverter</li><li>Cuidado com lã</li></ul>",
    "informacoes_produto": {
      "Capacidade": "11 quilogramas",
      "Cor": "Inox Look",
      "Marca": "Samsung",
      "Dimensões do produto": "65P x 60L x 85A centímetros",
      "Características especiais": "Cuidado com lã, Inverter"
    },
    "affiliate_url": "https://www.amazon.com.br/Lava-Seca-Samsung-Programas-Lavagem/dp/B0B61WJRY5?ref=dlx_deals_dg_dcl_B0B61WJRY5_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H4HYLQ71",
    "title": "Notebook Gamer Lenovo Loq 15irx9, 15.6\" Full Hd 144hz, Intel Core I5-13450hx, 16gb, 512gb Ssd, Nvidia Rtx 4050, Linux - 83khs00300",
    "image": "https://m.media-amazon.com/images/I/61+CippnCvL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 5899.0,
    "price_original": 6555.54,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 5,
    "coupon_code": null,
    "description": "<ul><li>Processador estável Intel Core i5-13450HX</li><li>Tela Gamer com taxa de 144Hz</li><li>Notebook Gamer Lenovo LOQ 15IRX9 i5 16GB 512GB SSD RTX 4050 144Hz</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ 15IRX9",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "512 GB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Linux",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "49 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-15irx9-I5-13450hx-Nvidia/dp/B0H4HYLQ71?ref=dlx_deals_dg_dcl_B0H4HYLQ71_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": true
  },
  {
    "asin": "B0C5DXJ165",
    "title": "Placa de Video Gigabyte RX 7600 Gaming OC, 8gb, GDDR6 - GV-R76GAMING-OC-8GD",
    "image": "https://m.media-amazon.com/images/I/71U03CcRZzL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1699.99,
    "price_original": 1952.93,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 452,
    "coupon_code": null,
    "description": "<ul><li>GPU GIGABYTE AMD RADEON</li><li>RX 7600 GAMING</li><li>8GB 128BITS GDDR6</li><li>GIGABYTE</li></ul>",
    "informacoes_produto": {
      "Coprocessador gráfico": "AMD Radeon RX 7600",
      "Marca": "GIGABYTE",
      "Tamanho da memória RAM da placa gráfica": "8.0",
      "Velocidade do clock da GPU": "2805 MHz",
      "Interface de saída de vídeo": "DisplayPort"
    },
    "affiliate_url": "https://www.amazon.com.br/Placa-Video-Gigabyte-Gaming-GDDR6/dp/B0C5DXJ165?ref=dlx_deals_dg_dcl_B0C5DXJ165_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B07VRYJWPB",
    "title": "Finish Power Powder Advanced Detergente para Lava Louças em Pó 2,5kg",
    "image": "https://m.media-amazon.com/images/I/61FuIlOh2GL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 98.78,
    "price_original": 146.59,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 22479,
    "coupon_code": null,
    "description": "<ul><li>Finish Power Powder Advanced é o seu detergente lava louças em pó que oferece limpeza profunda na dose certa. Recomendado pelos principais fabricantes de lava louças do Brasil e do mundo.</li><li>Sua louça do dia a dia vai ficar limpa de primeira, sem necessidade de pré-enxague. Possui ingredientes na fórmula que promovem o cuidado e proteção das louças.</li><li>Exclusiva fórmula com oxigênio ativo e enzimas que promovem limpeza através de sua ação desengordurante e da remoção de sujeiras.</li><li>Vem com medidor que ajuda a dosar corretamente a quantidade do detergente lava louças.</li><li>Usar lava louças remove até as sujeiras mais difíceis, sem bagunça, sem ressecar as mãos. É mais qualidade de vida!</li></ul>",
    "informacoes_produto": {
      "Marca": "Finish",
      "Forma do produto": "Pó",
      "Aroma": "Sem perfume",
      "Característica do material": "Sem perfume",
      "Número de itens": "4"
    },
    "affiliate_url": "https://www.amazon.com.br/Detergente-Para-Lou%C3%A7as-Finish-Advanced/dp/B07VRYJWPB?ref=dlx_deals_dg_dcl_B07VRYJWPB_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0918FHY6P",
    "title": "L'Oréal Professionnel Óleo 10 em 1 Absolut Repair | Multi-benefícios para cabelos secos e danificados | Repara e Promove Brilho | Com Gold Quinoa e Proteínas",
    "image": "https://m.media-amazon.com/images/I/61wfwHNv-NL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 123.39,
    "price_original": 247.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 22670,
    "coupon_code": null,
    "description": "<ul><li>Óleo de tratamento leave-in multibenefícios 10 em 1, que oferece nutrição, reparação instantânea e brilho para os fios</li><li>Sua fórmula profissional é enriquecida com Proteína do Trigo, garantindo uma restauração profunda e cabelos mais resistentes</li><li>Proporciona maciez e maleabilidade com um toque leve, sem pesar, facilitando o cuidado diário</li><li>Oferece proteção térmica e contra agressões externas, mantendo os cabelos saudáveis e protegidos no dia a dia</li><li>Repara a fibra capilar danificada, devolvendo a suavidade e o brilho para um resultado de salão instantâneo em casa</li></ul>",
    "informacoes_produto": {
      "Tipo de cabelo": "Fino",
      "Tipo de material livre": "Sem conservantes",
      "Aroma": "Sem perfume",
      "Volume líquido": "1 Onças líquidas"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Multi-benef%C3%ADcios-danificados-Prote%C3%ADnas/dp/B0918FHY6P?ref=dlx_deals_dg_dcl_B0918FHY6P_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GM1LSHQF",
    "title": "JBL, Fone de Ouvido Bluetooth Over-Ear, Tune 530BT, Sem Fio, Até 76 Horas de Bateria - Preto",
    "image": "https://m.media-amazon.com/images/I/61q9MOnS+2L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 199.0,
    "price_original": 299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 202,
    "coupon_code": null,
    "description": "<ul><li>SOM JBL PURE BASS POTENTE. O fone de ouvido JBL Tune 530BT entrega graves profundos e impactantes com drivers de 33 mm, proporcionando áudio dinâmico para músicas, vídeos e chamadas ao longo do dia.</li><li>ATÉ 76 HORAS DE BATERIA. O fone de ouvido Bluetooth JBL oferece longa duração para uso contínuo, com carga rápida que garante até 5 horas de reprodução em apenas 5 minutos, ideal para rotinas intensas.</li><li>CHAMADAS CLARAS COM 2 MICROFONES. Dois microfones beamforming captam sua voz com precisão e reduzem ruídos externos, proporcionando conversas nítidas mesmo em ambientes movimentados.</li><li>CONEXÃO MULTIPONTO BLUETOOTH 6.0. Alterne facilmente entre dois dispositivos conectados. O fone de ouvido Bluetooth JBL mantém áudio estável, sincronizado e com menor consumo de energia.</li><li>CONFORTO LEVE E DESIGN DOBRÁVEL. O fone de ouvido JBL conta com almofadas macias e estrutura leve para uso prolongado. Dobrável e prático, acompanha sua rotina com conforto e facilidade de transporte.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Cor": "Preto",
      "Colocação na orelha": "Extra-auriculares",
      "Fator de forma dos fones de ouvido": "Extra-auriculares",
      "Impedância": "20 Ohms"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-Ouvido-Bluetooth-Over-Ear-Bateria/dp/B0GM1LSHQF?ref=dlx_deals_dg_dcl_B0GM1LSHQF_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FJPL1MGY",
    "title": "Samsung Galaxy Watch Ultra 2025 Smartwatch 47mm LTE, Galaxy AI, Titânio Aeroespacial, Titânio Prata",
    "image": "https://m.media-amazon.com/images/I/518YXVYcCRL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 2099.0,
    "price_original": 4999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 66,
    "coupon_code": null,
    "description": "<ul><li>Titânio Aeroespacial e resistência</li><li>Até 100m de resistencia a água do mar</li><li>Bateria de até 100h</li><li>GPS duplo de alta precisão</li><li>Treinador de corrida avançado</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "Galaxy AI",
      "Capacidade de armazenamento da memória": "64 GB",
      "Capacidade da bateria": "590 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, NFC, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Galaxy-Watch-Smartwatch-Tit%C3%A2nio/dp/B0FJPL1MGY?ref=dlx_deals_dg_dcl_B0FJPL1MGY_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": true
  },
  {
    "asin": "B0FPRK5P9H",
    "title": "SEMP, Smart TV 4K UHD, 55“, Google TV, Google Assistente, Comando por Voz, Googlecast Integrado, Design Sem Bordas, Dolby Audio, 55S62",
    "image": "https://m.media-amazon.com/images/I/61mUtpPKNVL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 2099.99,
    "price_original": 2499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 166,
    "coupon_code": null,
    "description": "<ul><li>Smart TV com Google TV, Wi-Fi Dual Band, Bluetooth, Google Assistente, Dolby Audio, HDMI 2.1, HDR10+ e Googlecast Integrado</li><li>Tela 4K UHD de 55 polegadas com design sem bordas na cor preta, proporcionando imagem de alta resolução e visual moderno</li><li>Controle por comando de voz via Google Assistente para navegação prática entre aplicativos, conteúdos e configurações da TV</li></ul>",
    "informacoes_produto": {
      "Tamanho da tela": "55",
      "Marca": "Semp",
      "Tecnologia do visor": "4K UHD, LCD, OLED, UHD",
      "Resolução": "4K",
      "Taxa de atualização": "60 Hz",
      "Características especiais": "Google Assistente, Dolby Audio, HDMI 2.1, HDR10+, Googlecast Integrado, design sem bordas",
      "Componentes incluídos": "01 Televisor 55\", 01 Controle Remoto, 1 Cabo Adaptador P2/RCA",
      "Tecnologia de conectividade": "HDMI, USB, Wi-fi",
      "Proporção de tela": "16:9",
      "Dimensões do produto": "71,1P x 122,6L x 7,3A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SEMP-SMART-55S62-UHD-GOOGLE/dp/B0FPRK5P9H?ref=dlx_deals_dg_dcl_B0FPRK5P9H_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": true
  },
  {
    "asin": "B09GSQMVJS",
    "title": "L'Oréal Professionnel Inforcer Shampoo Fortificante Antiqueda por Quebra, Crescimento Saudável Para Cabelos Frágeis e Quebradiços Com Biotina e Vitamina B6, 300ml",
    "image": "https://m.media-amazon.com/images/I/51TvgvfNA9L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 67.4,
    "price_original": 116.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7268,
    "coupon_code": null,
    "description": "<ul><li>Um tratamento em shampoo que limpa, fortalece e proporciona uma ação anti-quebra instantânea nos fios.</li><li>Enriquecido com Biotina e Vitamina B6, que estimulam o crescimento saudável e o metabolismo de proteínas.</li><li>Leva nutrientes à fibra capilar, promovendo força instantânea e prevenindo o ressecamento e a quebra.</li><li>Com o uso contínuo, os cabelos se tornam mais resistentes, com menos queda e com um crescimento visível.</li><li>Conquiste cabelos suplementados com força, nutridos, resistentes e com o crescimento saudável que você deseja.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Líquido",
      "Tipo de cabelo": "Todos os tipos de cabelos",
      "Aroma": "Sem perfume",
      "Faixa etária (descrição)": "Adulto"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Fortificante-Anti-Quebra-Quebradi%C3%A7os/dp/B09GSQMVJS?ref=dlx_deals_dg_dcl_B09GSQMVJS_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GL3YFDQ9",
    "title": "Samsung Ar Condicionado Split Inverter Samsung WindFree AI 24000 BTU/h Frio AR60F24D1AWNAZ - 220 Volts",
    "image": "https://m.media-amazon.com/images/I/51HhpshEOKL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 3599.0,
    "price_original": 4419.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Tipo de Produto: Ar Condicionado Split com tecnologia Inverter da marca Samsung</li><li>Capacidade de Refrigeração: Sistema com 24000 BTU/h que proporciona climatização eficiente para ambientes amplos</li><li>Tecnologia WindFree: Modo sem vento que dispersa o ar através de 23.000 microfuros, eliminando o vento gelado direto e proporcionando maior conforto</li><li>Inteligência Artificial: Sistema AI que aprende as preferências do usuário e compara com temperaturas interna e externa para climatização automática e economia de energia</li><li>Conectividade Inteligente: Controle via WiFi através do app SmartThings com compatibilidade para comandos de voz por Bixby, Alexa e Google Assistente</li><li>Eficiência Energética: Classificação A no Inmetro com economia de até 77% de energia e monitoramento de consumo em tempo real</li><li>Modo Welcome Cooling: Climatização automática que detecta sua localização via smartphone e liga o aparelho quando você se aproxima de casa</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Capacidade": "2 tons",
      "Dimensões do produto": "38P x 111L x 30A centímetros",
      "Cor": "Branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Condicionado-Inverter-WindFree-AR60F24D1AWNAZ/dp/B0GL3YFDQ9?ref=dlx_deals_dg_dcl_B0GL3YFDQ9_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": true
  },
  {
    "asin": "B000WLN7AM",
    "title": "Whisky Bourbon Maker's Mark 750ml",
    "image": "https://m.media-amazon.com/images/I/7199P9zzMGL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 119.9,
    "price_original": 145.33,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3369,
    "coupon_code": null,
    "description": "<ul><li>Com coloração âmbar, laranja-amarelada, o bourbon tornou-se um dos destilados mais apreciados no mundo.</li><li>Diferentemente da composição do whisky tradicional, o Maker’s Mark não possui centeio na sua formulação, e sim, trigo doce e vermelho de inverno, milho e cevada.</li><li>O sucesso é fruto de um processo produtivo minucioso, que segue à risca os padrões de qualidade.</li><li>A produção é feita em baixa escala, em lotes individuais que não ultrapassam 19 barris por lote.</li><li>O Maker’s Mark é envelhecido por cerca de seis anos, depois de engarrafado é então selado em uma garrafa de forma única e selada com a cera vermelha na rolha.</li></ul>",
    "informacoes_produto": {
      "Marca": "Maker's Mark",
      "Tipo de álcool": "Bourbon",
      "Sabor": "Chocolate",
      "Contagem de unidades": "750.0 Mililitro",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Whiskey-MakerS-Mark-Makers-Sabor/dp/B000WLN7AM?ref=dlx_deals_dg_dcl_B000WLN7AM_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D81JTSGX",
    "title": "Lavadora de Roupas 13kg Branca Midea Wave Agitator 127V",
    "image": "https://m.media-amazon.com/images/I/41WaSpk6xDL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1800.0,
    "price_original": 2199.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 21,
    "coupon_code": null,
    "description": "<ul><li>Lavadora Top Load</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "59,6P x 58L x 101,5A centímetros",
      "Marca": "Midea",
      "Capacidade": "13 quilogramas",
      "Características especiais": "Alta eficiência",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/Lavadora-Roupas-Branca-Midea-Agitator/dp/B0D81JTSGX?ref=dlx_deals_dg_dcl_B0D81JTSGX_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B07FN1MZBH",
    "title": "Controle Dualshock 4 - PlayStation 4 - Preto",
    "image": "https://m.media-amazon.com/images/I/61kwdPH8+xL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 249.0,
    "price_original": 349.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 27011,
    "coupon_code": null,
    "description": "<ul><li>Revolucionário, intuitivo e preciso: o controle sem fio DualShock4 para o sistema PlayStation4 define esta geração de jogos, combinando recursos revolucionários e conforto com controles precisos e intuitivos.</li><li>Controle preciso: o toque, formato e a sensibilidade dos controles analógicos e botões com gatilho do DualShock4 oferecem aos jogadores conforto e controle absolutos em todos os jogos para PlayStation4.</li><li>Compartilhamento em suas mãos: o botão SHARE facilita o compartilhamento dos seus melhores momentos nos jogos, basta pressionar um botão. Faça upload de vídeos de gameplay e capturas de tela diretamente do seu sistema ou transmita seu gameplay ao vivo, tudo isso sem afetar o andamento do jogo.</li><li>Recursos inovadores: recursos revolucionários, como o touch pad, a barra de luz e o alto-falante integrados proporcionam formas incríveis de jogar e interagir com seus jogos, e seu conector de áudio de 3,5 mm oferece uma prática solução de áudio pessoal para os jogadores que preferirem jogar com mais privacidade.</li><li>Recarga eficiente: é fácil recarregar o controle sem fio DualShock4, basta conectá-lo ao seu sistema PlayStation4 (mesmo em modo de espera), ou qualquer carregador padrão com uma porta micro USB</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Controle-Dualshock-PlayStation-4-Preto/dp/B07FN1MZBH?ref=dlx_deals_dg_dcl_B07FN1MZBH_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FHJ6WS8V",
    "title": "Notebook Lenovo IdeaPad 1 15AMN7 AMD Ryzen 5 7520U 8GB 512GB SSD Windows 11 15.6\" - 82X5000NBR Cloud Grey",
    "image": "https://m.media-amazon.com/images/I/519KvpZ9iBL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 3629.0,
    "price_original": 3899.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 67,
    "coupon_code": null,
    "description": "<ul><li>Tela HD de 15,6\" com moldura ultrafina para melhor imersão</li><li>Áudio estéreo Dolby Audio para som mais rico</li><li>Webcam HD, que oferece um obturador de privacidade</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "IdeaPad 1 15AMN7",
      "Tamanho da tela": "15,6 Polegadas",
      "Cor": "Cinza",
      "Tamanho do disco rígido": "512 GB",
      "Modelo da CPU": "Ryzen 5",
      "Tamanho instalado da memória RAM": "8 GB",
      "Sistema operacional": "Windows 11 Home Single Language",
      "Descrição da placa de vídeo": "Gráficos integrados AMD Radeon 610M",
      "Velocidade da CPU": "2,8 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-IdeaPad-15AMN7-Windows/dp/B0FHJ6WS8V?ref=dlx_deals_dg_dcl_B0FHJ6WS8V_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FL2QF7YJ",
    "title": "JBL, Caixa de Som, PartyBox Encore Essential 2, Show de Luzes, Bluetooth, Portátil, Resistente a Respingos, Bateria de até 15h, Som JBL Pro Sound, AI Sound Boost, 100 W RMS",
    "image": "https://m.media-amazon.com/images/I/71Ar78y955L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1328.99,
    "price_original": 1899.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 459,
    "coupon_code": null,
    "description": "<ul><li>SOM POTENTE COM AI SOUND BOOST. O JBL Pro Sound ganha ainda mais potência com o AI Sound Boost, oferecendo agudos nítidos e graves impactantes, mesmo em alto volume e ambientes amplos.</li><li>SHOW DE LUZES NO RITMO DA MÚSICA. Os efeitos de luzes dinâmicas criam o clima ideal para qualquer festa, com padrões vibrantes e estroboscópicos que seguem o ritmo da sua playlist do começo ao fim.</li><li>DURAÇÃO PARA O DIA TODO. A bateria integrada oferece até 15 horas de reprodução contínua com uma única carga.</li><li>TECNOLOGIA AURACAST. É possível emparelhar com outro JBL PartyBox Encore Essential 2 ou conectar várias caixas via JBL Auracast para ampliar sua experiência sonora.</li><li>DESIGN RESISTENTE. Com alça prática para transporte e proteção contra respingos (IPX4), a PartyBox Encore Essential 2 está pronta para festas em qualquer ambiente ou clima.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Dimensões do item C x L x A": "29 x 33 x 28 centímetros",
      "Tecnologia de conectividade": "Bluetooth",
      "Cor": "Preto",
      "Dispositivos compatíveis": "Leitor de MP3, Notebook, Smartphone, Tablet"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-PartyBox-Essential-Bluetooth-Respingos/dp/B0FL2QF7YJ?ref=dlx_deals_dg_dcl_B0FL2QF7YJ_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": true
  },
  {
    "asin": "B09LHWJF1F",
    "title": "Forno de Embutir Oster Elétrico, 77L, Black, 220V, OFOR7740",
    "image": "https://m.media-amazon.com/images/I/414Xyz+L2FL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1454.53,
    "price_original": 2199.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 26,
    "coupon_code": null,
    "description": "<ul><li>CONFIRA AS MEDIDAS IDEIAS PARA INSTALAR ESTE FORNO NA SUA COZINHA E A VOLTAGEM DO PRODUTO: Medidas correspondentes ao nicho para embutir o produto. Veja mais informações no manual.</li><li>GRANDE NA CAPACIDADE E ENORME NA BELEZA: Com o tamanho de 77 litros, você vai poder preparar diferentes tipos de receitas: de sobremesas a assados.</li><li>FUNÇÕES PRÉ-PROGRAMADAS: Programe o seu preparo com segurança, sabendo o horário que vai iniciar e terminar. Segurança, praticidade e eficiência.</li><li>AJUSTE DE ALTURA E BANDEJA COLETORA: Posicione a grade de acordo com o resultado desejado. A bandeja coletora garante facilidade para a limpeza.</li><li>TIMER DE ATÉ 120 MINUTOS: Você pode programar o preparo de receitas mais longas por até 120 minutos sem interrupções.</li></ul>",
    "informacoes_produto": {
      "Tamanho": "29,55 Kg",
      "Marca": "Oster",
      "Cor": "preto",
      "Método de aquecimento": "Convecção",
      "Tipo de acabamento": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/Forno-Embutir-El%C3%A9trico-Oster-Black/dp/B09LHWJF1F?ref=dlx_deals_dg_dcl_B09LHWJF1F_dt_sl14_88_pi&pf_rd_r=09C5Y67QMQJAK5QN0MW1&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:00:25.000Z",
    "spotlight": true
  }
];
