const PRODUCTS = [
  {
    "asin": "index-0",
    "title": "Pilha Alcalina, Elgin, Palito AAA, Blister com 4",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71faB-DYcoL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 6.66,
    "price_original": 11.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 31653,
    "coupon_code": null,
    "description": "<ul><li>Embalagem com 4 pilhas alcalinas tipo AAA Palito</li><li>Alta Durabilidade na Carga.</li><li>Composição livre de metais pesados que são prejudiciais à saúde.</li><li>Aprovadas por laboratórios credenciados pelo INMETRO.</li><li>Ideal para aparelhos que requerem descargas de energia rápidas e fortes.</li><li>As alcalinas AAA da Elgin receberam os selos Melhor do Teste e Escolha Certa da Proteste de pilhas com melhor desempenho.</li><li>Validade 5 anos.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AAA (necessita de baterias)",
      "Marca": "Elgin",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "300 Amperes Horas",
      "Adequação do controle por rádio": "Diversos"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilhas-Alcalinas-Palito-Elgin-Baterias/dp/B0754J12RW/ref=zg_bs_g_electronics_d_sccl_1/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-4",
    "title": "Suporte Portátil para Notebook de 10” a 17,3” Dobrável com 10 Níveis de Regulagem, Base Ergonômica em Alumínio, Ventilação Aprimorada e Bolsa para Transporte",
    "image": "https://images-na.ssl-images-amazon.com/images/I/615PonH2F3L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Móveis",
    "price_current": 18.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 23240,
    "coupon_code": null,
    "description": "<ul><li>Blister Com 4 Pilhas AAA de 1000Mah.</li><li>Energia renovável de alta qualidade, as pilhas recarregáveis da Elgin suportam até 1000 recargas.</li><li>Aprovadas pelo INMETRO: As Pilhas Elgin Energy são testadas periodicamente por laboratórios credenciados pelo INMETRO, para garantir a qualidade e conformidade com a resolução Conama 401.</li><li>Ecologicamente corretas: As Pilhas da Elgin têm 0% de Mercúrio e Cadmio em sua composição, colaborando para a preservação do meio ambiente.</li><li>Indicada para brinquedos, controle de videogames e produtos de alto consumo de pilha.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AAA (necessita de baterias)",
      "Marca": "Elgin",
      "Composição das células da bateria": "NiMH",
      "Capacidade da bateria": "1000",
      "Adequação do controle por rádio": "Brinquedos"
    },
    "affiliate_url": "https://www.amazon.com.br/Regulagem-Ergon%C3%B4mica-Ventila%C3%A7%C3%A3o-Aprimorada-Transporte/dp/B0H3788T72/ref=zg_bs_g_furniture_d_sccl_5/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-5",
    "title": "Garrafa Squeeze TIBA Fun 300 ml",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71ufMhXlQZL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 10.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 177,
    "coupon_code": null,
    "description": "<ul><li>Linha Garrafa Squeeze TIBA 300 ml</li><li>Garrafa Squeze com alça, tampa antivazamento e acabamento soft toutch.</li><li>Pode ir na lava-louças e no microondas e ser utilizada com bebidas quentes e bebidas geladas</li><li>Medida: 12,5 X 6,5 cm</li></ul>",
    "informacoes_produto": {
      "Marca": "TIBA",
      "Material": "PP",
      "Tipo de garrafa": "Garrafa Squeeze com Alça",
      "Cor": "Azul",
      "Capacidade": "300 ml"
    },
    "affiliate_url": "https://www.amazon.com.br/Garrafa-Squeeze-TIBA-Fun-300/dp/B0G1PCXPNC/ref=zg_bs_g_kitchen_d_sccl_6/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-6",
    "title": "Oikos - Kit 3 Sacos para Lavar Roupas Delicadas P,M e G com Zíper | Camisetas, proteção dos tecidos, roupas íntimas, máquina de lavar, reutilizáveis",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61BJhE0GLIL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 19.9,
    "price_original": 25.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4320,
    "coupon_code": null,
    "description": "<ul><li>Com 3 tamanhos diferentes: comportam desde a roupa íntima até roupa de cama, protegendo os tecidos durante a lavagem - principalmente os mais finos e delicados.</li><li>Funcionais: eles mantêm a qualidade das peças e ainda deixam as roupas sem aquelas bolinhas e nem fiapos.</li><li>Multiusos: também são bem legais na hora de organizar a mala de viagem e para proteger aquelas roupas que não são usadas no dia a dia dentro do armário.</li><li>Acabamento no zíper: seu zíper tem um compartimento próprio para não desfiar as roupas enquanto a lavagem acontece na máquina.</li><li>Fácil de limpar: pode ser lavado normalmente na água corrente com sabão, ou na máquina de lavar.</li></ul>",
    "informacoes_produto": {
      "Marca": "OIKOS",
      "Material": "Plástico, Poliéster",
      "Cor": "Branco",
      "Dimensões do produto": "40C x 50L x 0,3A centímetros",
      "Características especiais": "Acabamento no zíper, Fácil de limpar"
    },
    "affiliate_url": "https://www.amazon.com.br/Oikos-conjunto-m%C3%A1quina-roupas-delicadas/dp/B086WWQX1S/ref=zg_bs_g_appliances_d_sccl_7/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-7",
    "title": "Vonder, Fita Crepe 24 Mm X 50 M.",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51AMR+GJ5uL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 13.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4323,
    "coupon_code": null,
    "description": "<ul><li>Com 3 tamanhos diferentes: comportam desde a roupa íntima até roupa de cama, protegendo os tecidos durante a lavagem - principalmente os mais finos e delicados.</li><li>Funcionais: eles mantêm a qualidade das peças e ainda deixam as roupas sem aquelas bolinhas e nem fiapos.</li><li>Multiusos: também são bem legais na hora de organizar a mala de viagem e para proteger aquelas roupas que não são usadas no dia a dia dentro do armário.</li><li>Acabamento no zíper: seu zíper tem um compartimento próprio para não desfiar as roupas enquanto a lavagem acontece na máquina.</li><li>Fácil de limpar: pode ser lavado normalmente na água corrente com sabão, ou na máquina de lavar.</li></ul>",
    "informacoes_produto": {
      "Marca": "OIKOS",
      "Material": "Plástico, Poliéster",
      "Cor": "Branco",
      "Dimensões do produto": "40C x 50L x 0,3A centímetros",
      "Características especiais": "Acabamento no zíper, Fácil de limpar"
    },
    "affiliate_url": "https://www.amazon.com.br/Fita-crepe-24-50-Vonder/dp/B07GH8YBGB/ref=zg_bs_g_hi_d_sccl_8/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-8",
    "title": "Loctite Super Bonder Mega, Adesivo instantâneo para reparos, Cola transparente para materiais diversos com acabamento profissional, 1x20g",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61+xfkF6gwL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 10.99,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 3516,
    "coupon_code": null,
    "description": "<ul><li>Streaming simplificado: com a plataforma de streaming para TV nº 1 dos Estados Unidos*, é fácil e divertido descobrir apps populares, além de milhares de filmes, séries, esportes e TV ao vivo. *Baseado em horas de streaming—Hypothesis Group</li><li>Transforme sua TV em uma Smart TV de verdade com o Roku Streaming Stick.</li><li>O design compacto do Roku Streaming Stick não bloqueia as entradas HDMI vizinhas e pode ser alimentado pela porta USB da sua TV. Ele se conecta diretamente à parte de trás da sua TV e fica super discreto. Sem tomada, sem cabos extras, sem bagunça.</li><li>Chega de usar vários controles remotos: ligue a TV, ajuste o volume e controle o dispositivo Roku com um controle remoto. Use a voz para pesquisar rápido, assistir ao seu conteúdo favorito e muito mais.</li><li>Leve sua TV favorita com você: com o design portátil desse dispositivo de streaming, você pode levar sua TV na mala quando estiver viajando, sem precisar fazer login no dispositivo de outra pessoa.</li><li>Todos os principais apps: você não vai mais precisar perguntar “Onde está passando?\". Agora todos os principais apps estão em um só lugar, para que você possa sempre fazer streaming dos seus programas de TV, filmes favoritos e muito mais.</li><li>Fácil de usar: comece imediatamente com uma tela inicial que dá acesso ao que você quer assistir de forma rápida.</li><li>TV ao vivo gratuita de verdade: aproveite dezenas de canais com notícias ao vivo, esportes, dramas e muito mais - tudo isso totalmente de graça.</li><li>Configuração rápida e fácil: basta ligar seu dispositivo, conectar-se à internet e mergulhar em um mundo de streaming.</li></ul>",
    "informacoes_produto": {
      "Marca": "Roku",
      "Tecnologia de conectividade": "Wi-fi",
      "Tipo de conector": "HDMI",
      "Características especiais": "Compatível com Apple AirPlay e HomeKit, Compatível com Google Home, Compatível com Alexa",
      "Resolução": "1080p"
    },
    "affiliate_url": "https://www.amazon.com.br/Super-Bonder-Ultra-20g-Loctite/dp/B07SYBNBNF/ref=zg_bs_g_hi_d_sccl_9/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-9",
    "title": "LYOR - Bandeja de Bambu Hire Marrom Natural 28cm - Mesa Posta - Organização - Utensílios de Cozinha - Enxoval - Decoração - Travessa Retangular - Petisqueira - Utilidades Domésticas",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61HSWjR-MQL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 17.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 11970,
    "coupon_code": null,
    "description": "<ul><li>Para começar a usar o Galaxy Fit3, uma conta Samsung deve estar cadastrada em seu celular. Seus dados de saúde no seu Galaxy Fit3 serão transferidos com segurança e armazenados na Samsung Cloud conectada à sua conta, para que você possa acessar e gerenciar totalmente seus dados.</li><li>Quando a bateria estiver completamente descarregada, o Fit não ligará. Carregue totalmente o bateria antes de ligar o Fit.</li><li>A tela sensível ao toque pode funcionar mal em condições úmidas ou quando exposta à água.</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "FreeRTOS",
      "Capacidade de armazenamento da memória": "16 MB",
      "Características especiais": "Leve",
      "Capacidade da bateria": "3000 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/LYOR-Bandeja-Bambu-Marrom-Natural/dp/B08X1B72TP/ref=zg_bs_g_kitchen_d_sccl_10/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-11",
    "title": "Controle Remoto Tv Samsung Smart",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41xgru2Y8tL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 8.5,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 1073,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {
      "Material": "Carvão",
      "Dimensões do produto": "12P x 30L x 8A centímetros",
      "Peso do produto": "600 Gramas",
      "Vantagens do produto": "Remove impurezas e contaminantes",
      "Marca": "SOFT"
    },
    "affiliate_url": "https://www.amazon.com.br/Controle-Remoto-Tv-Samsung-Smart/dp/B08B4DJNX8/ref=zg_bs_g_electronics_d_sccl_12/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-14",
    "title": "Vonder, Adesivo Instantâneo Cianoacrilato, Industrial, 20 g.",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41H-uQW4CGL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 8.82,
    "price_original": 8.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 41,
    "coupon_code": null,
    "description": "<ul><li>Conteúdo da embalagem: 20 g</li><li>Cura inicial: 4,0 s</li><li>Cura total: 24 h</li><li>Aspecto/aparência: Líquido incolor</li><li>Temperatura de trabalho: -55°C a 85°C</li></ul>",
    "informacoes_produto": {
      "Marca": "VONDER",
      "Usos específicos do produto": "Vários",
      "Material": "Cianoacrilato",
      "Forma do produto": "Líquido",
      "Características especiais": "Secagem rápida"
    },
    "affiliate_url": "https://www.amazon.com.br/Vonder-Adesivo-Instant%C3%A2neo-20g/dp/B08M416H6P/ref=zg_bs_g_hi_d_sccl_15/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-15",
    "title": "Disjuntor Monopolar MCB Curva C 3KA 16A Elgin - 1 Polo, 16 Amperes, Mini",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51FzVJcWIxL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 6.5,
    "price_original": 8.12,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 104,
    "coupon_code": null,
    "description": "<ul><li>Mini disjuntor Termomagnético Elgin 1 polo 16A</li><li>Modelos de 10A a 50A</li><li>Alto nível de proteção de cabos</li><li>Curva de disparo tipo C</li><li>Travamento da manopla</li></ul>",
    "informacoes_produto": {
      "Marca": "Elgin",
      "Classificação de corrente": "16 Amperes",
      "Dimensões do produto": "70P x 18L x 81A milímetros",
      "Tipo de disjuntor": "Disjuntor Termomagnético Monopolar",
      "Tipo de montagem": "Montagem em painel"
    },
    "affiliate_url": "https://www.amazon.com.br/Disjuntor-Monopolar-MCB-Curva-Elgin/dp/B0B2K38C8Y/ref=zg_bs_g_hi_d_sccl_16/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-16",
    "title": "LYOR - Mini Mixer Misturador Elétrico para Bebidas - Inox e Plástico Branco - Eficiente e Compacto para Batidas e Misturas Rápidas",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41PfSxzi5qL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 9.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 62227,
    "coupon_code": null,
    "description": "<ul><li>Auto desligamento quando as pilhas carregam 100%</li><li>Proteção que garante o carregamento seguro</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "2500",
      "Adequação do controle por rádio": "Aparelho auditivo, Controle remoto da TV, Câmera, Drone, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Mixer-El%C3%A9trico-Bebidas-Pl%C3%A1stico-Branco/dp/B0C7DLXV6Q/ref=zg_bs_g_kitchen_d_sccl_17/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-17",
    "title": "Farinha de Trigo de 1 Kg, Tipo 1, Globo Superiore W300.",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61oZUBexZ7L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 5.49,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 202,
    "coupon_code": null,
    "description": "<ul><li>SOM JBL PURE BASS POTENTE. O fone de ouvido JBL Tune 530BT entrega graves profundos e impactantes com drivers de 33 mm, proporcionando áudio dinâmico para músicas, vídeos e chamadas ao longo do dia.</li><li>ATÉ 76 HORAS DE BATERIA. O fone de ouvido Bluetooth JBL oferece longa duração para uso contínuo, com carga rápida que garante até 5 horas de reprodução em apenas 5 minutos, ideal para rotinas intensas.</li><li>CHAMADAS CLARAS COM 2 MICROFONES. Dois microfones beamforming captam sua voz com precisão e reduzem ruídos externos, proporcionando conversas nítidas mesmo em ambientes movimentados.</li><li>CONEXÃO MULTIPONTO BLUETOOTH 6.0. Alterne facilmente entre dois dispositivos conectados. O fone de ouvido Bluetooth JBL mantém áudio estável, sincronizado e com menor consumo de energia.</li><li>CONFORTO LEVE E DESIGN DOBRÁVEL. O fone de ouvido JBL conta com almofadas macias e estrutura leve para uso prolongado. Dobrável e prático, acompanha sua rotina com conforto e facilidade de transporte.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Cor": "Preto",
      "Colocação na orelha": "Extra-auriculares",
      "Fator de forma dos fones de ouvido": "Extra-auriculares",
      "Impedância": "20 Ohms"
    },
    "affiliate_url": "https://www.amazon.com.br/Farinha-Trigo-Tipo-Globo-Superiore/dp/B0BLP86QT3/ref=zg_bs_g_kitchen_d_sccl_18/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-18",
    "title": "Suporte Para Notebook E MacBook em Alumínio com Altura Ajustável",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61Ggc5CthJL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 18.49,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 38800,
    "coupon_code": null,
    "description": "<ul><li>SUPORTE FIXO DE PAREDE: Construído com aço de alta resistência, o suporte GENIUS da ELG oferece segurança incomparável. Seu sistema de encaixe rápido e trava de segurança garantem praticidade na instalação e uso diário.</li><li>DURÁVEL E CONFIÁVEL: Com uma garantia total de 5 anos contra defeitos de fabricação ou em suas peças, o suporte GENIUS da ELG demonstra a confiança da marca em sua qualidade superior.</li><li>ACABAMENTO PREMIUM: O acabamento em pintura eletrostática não é apenas esteticamente agradável, mas também funcional. Esta tecnologia avançada proporciona maior durabilidade ao produto e resistência superior a riscos.</li><li>FÁCIL INSTALAÇÃO: Graças ao gabarito e kit de acessórios inclusos. Seja em parede de madeira ou alvenaria, você terá todas as ferramentas necessárias para uma montagem fácil e segura.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "ELG",
      "Material": "Aço carbono",
      "Cor": "PRETO"
    },
    "affiliate_url": "https://www.amazon.com.br/Suporte-Notebook-MacBook-Alum%C3%ADnio-Ajust%C3%A1vel/dp/B086CB6BXW/ref=zg_bs_g_computers_d_sccl_19/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-19",
    "title": "Case para HD transparente, Usb 3.0, transmissão 6gbps, Sata 2.5\", Hhd ou Ssd, Ecase-300",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51540QJMhjL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 13.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 38817,
    "coupon_code": null,
    "description": "<ul><li>SUPORTE FIXO DE PAREDE: Construído com aço de alta resistência, o suporte GENIUS da ELG oferece segurança incomparável. Seu sistema de encaixe rápido e trava de segurança garantem praticidade na instalação e uso diário.</li><li>DURÁVEL E CONFIÁVEL: Com uma garantia total de 5 anos contra defeitos de fabricação ou em suas peças, o suporte GENIUS da ELG demonstra a confiança da marca em sua qualidade superior.</li><li>ACABAMENTO PREMIUM: O acabamento em pintura eletrostática não é apenas esteticamente agradável, mas também funcional. Esta tecnologia avançada proporciona maior durabilidade ao produto e resistência superior a riscos.</li><li>FÁCIL INSTALAÇÃO: Graças ao gabarito e kit de acessórios inclusos. Seja em parede de madeira ou alvenaria, você terá todas as ferramentas necessárias para uma montagem fácil e segura.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "ELG",
      "Material": "Aço carbono",
      "Cor": "PRETO"
    },
    "affiliate_url": "https://www.amazon.com.br/Case-transparente-original-transmiss%C3%A3o-6gbps/dp/B07K2F1B2S/ref=zg_bs_g_computers_d_sccl_20/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-20",
    "title": "Cabo de carregador de iPhone Fast/Carga Rápida USB C Lightning Cabo Certificação MFi Tipo C Cabo de Carregamento para iPhone 13/13 Pro /12/12 Pro/Max/11/11Pro/XS/Max/XR/X/8/8Plus",
    "image": "https://images-na.ssl-images-amazon.com/images/I/31vvbOazPBL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 6.5,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 11363,
    "coupon_code": null,
    "description": "<ul><li>Revestimento Dura Mais: Não deixam o alimento grudar, tem maior durabilidade e é fácil de limpa.</li><li>2 em 1 (Grill e Sanduicheira) : Prepare saborosos sanduíches, hambúrgueres , carnes, peixe, vegetais e muito mais.</li><li>Chapa superior Grill e chapa inferior lisa: Ideal para preparar diversas receitas.</li><li>Placa superior de aquecimento ajustável: Prepara alimentos de diversas espessuras sem amassar.</li><li>Compacta, prática e mais saudável: Não precisa usar óleo, proporcionando alimentos mais saudáveis.</li></ul>",
    "informacoes_produto": {
      "Cor": "Inox",
      "Material": "Plástico e Metal",
      "Marca": "Britânia",
      "Dimensões do produto": "22P x 26L x 8A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/carregador-iPhone-Lightning-Certifica%C3%A7%C3%A3o-Carregamento/dp/B0BGJR1R3B/ref=zg_bs_g_computers_d_sccl_21/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-21",
    "title": "Adaptador Para Tomada Pino Multiplicador Tripolar Branco, Force Line, 0180100004",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51qKwhr1AgL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 8.1,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3942,
    "coupon_code": null,
    "description": "<ul><li>🔒 Potes de Vidro Hermético com Tampa 4 Travas e Silicone – Sistema de vedação hermética com anel de silicone removível que conserva alimentos por mais tempo. Ideal como pote de vidro com tampa para armazenamento seguro sem vazamentos.</li><li>🔥 Recipiente de Vidro 640ml para Micro-ondas, Forno e Freezer – Pote de vidro resistente a altas temperaturas (até 300°C), pode ir ao microondas, freezer e forno sem tampa. Perfeito para marmita de vidro e armazenamento térmico.</li><li>🌱 Pote de Vidro Livre de BPA para Armazenar Alimentos – Alternativa saudável aos potes plásticos. Não absorve odores, não mancha e mantém sabor original. Ideal para organização de cozinha e conservação de alimentos.</li><li>🍱 Kit 5 Potes de Vidro Retangular 640ml para Marmita e Meal Prep – Conjunto de recipientes de vidro herméticos para preparar marmitas, guardar arroz, feijão, massas, saladas e refeições prontas.</li><li>🧼 Organizador de Alimentos em Vidro Transparente Fácil de Limpar – Design empilhável, vidro durável e tampa desmontável que facilita higienização. Excelente para organização de geladeira, armário e despensa.</li></ul>",
    "informacoes_produto": {
      "Marca": "GATO PANDA",
      "Cor": "Azul",
      "Material": "Vidro borossilicato",
      "Característica do material": "Seguro para forno, Seguro para micro-ondas, Sem BPA",
      "Capacidade": "640 ml"
    },
    "affiliate_url": "https://www.amazon.com.br/Pino-Multiplicador-Tripolar-0180100004-Forceline/dp/B0777S9WRF/ref=zg_bs_g_hi_d_sccl_22/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-22",
    "title": "Brilhus - Luva de Látex Versátil, Tamanho M, Cor Amarela, Bettanin",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71UjjRw0OJL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 8.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 4348,
    "coupon_code": null,
    "description": "<ul><li>DIFERENCIAIS: A Panela de Pressão Brinox Ceramic Life Pressure com indução foi desenvolvida para agilizar o preparo das refeições do dia a dia. Com capacidade de 4,2 litros, oferece eficiência no cozimento, praticidade no uso e desempenho confiável para diferentes receitas.</li><li>MATERIAIS: O corpo da panela é produzido em alumínio, material que favorece a condução do calor e contribui para uma cocção mais rápida e uniforme. Os cabos e alças são fabricados em baquelite antitérmico, garantindo segurança no manuseio.</li><li>COMPOSIÇÃO: Possui revestimento interno antiaderente Ceramic Life, com classificação A (ótima) de antiaderência, facilitando o preparo dos alimentos e a limpeza. O sistema de pressão conta com três dispositivos de segurança: trava de segurança, válvula de trabalho e válvula de segurança.</li><li>INSTRUÇÕES DE USO E RECOMENDAÇÕES: Antes do primeiro uso, recomenda-se realizar a cura do revestimento. Após o preparo, evitar choques térmicos e efetuar a limpeza manual com esponja macia e detergente neutro, sem utilizar produtos abrasivos.</li><li>TIPOS DE FOGÕES: Compatível com fogões a gás, elétricos, vitrocerâmicos e por indução, graças ao fundo preparado para esse tipo de uso. Não deve ser utilizada em forno, micro-ondas ou lava-louças.</li><li>RESUMO: Funcional e prática, a Panela de Pressão Brinox Ceramic Life Pressure é indicada para o preparo de carnes, grãos, legumes e receitas que exigem cozimento sob pressão, oferecendo agilidade e desempenho no uso diário.</li></ul>",
    "informacoes_produto": {
      "Marca": "Brinox",
      "Capacidade": "4,2 litros",
      "Material": "Alumínio",
      "Cor": "Vanilla",
      "Tipo de acabamento": "Brilhante"
    },
    "affiliate_url": "https://www.amazon.com.br/Vers%C3%A1til-Tamanho-Brilhus-Bettanin-Amarelo/dp/B08Y55DZXT/ref=zg_bs_g_hi_d_sccl_23/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-23",
    "title": "Fita Isolante Foxlux PVC Antichamas 10m x 19mm Preta 600V Alta Elasticidade Espessura 0,15mm",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61VKmSOZZnL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 6.34,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 5813,
    "coupon_code": null,
    "description": "<ul><li>MÁQUINA NESCAFÉ DOLCE GUSTO: cápsulas para o sistema Nescafé Dolce Gusto. Conheça uma das mais de 35 opções de bebidas incríveis! As máquinas e cafeteiras Nescafé Dolce Gusto podem fazer em casa suas bebidas favoritas da cafeteria: basta apertar um botão!</li><li>MOCHACCINO AVELÃ: Um verdadeiro deleite! Você só precisa de uma xícara do Mochaccino Avelã para saborear um sabor que é puro conforto! É a magia do aroma de café e o toque de sabor avelã que vai fazer você se sentir abraçado! São 10 cápsulas para aproveitar e saborear.</li><li>MODO DE PREPARO: após preencher o recipiente da sua máquina Nescafé Dolce Gusto com água, coloque uma cápsula Nescafé Dolce Gusto Mochaccino Avelã, ajuste a quantidade de água sugerida, que são 4 níveis e ligue sua máquina no modo quente.</li><li>NOSSO COMPROMISSO COM O PLANETA: 100% do nosso café é certificado por parceiros especializados. Isso quer dizer que além de sabermos de onde vem cada xícara de café. Você sabia que é fácil reciclar suas cápsulas de Nescafé Dolce Gusto? Basta colocar as cápsulas usadas em um saco ou caixa de papelão para que não suje ou molhe os outros materiais recicláveis. E caso haja muito líquido nas cápsulas, você pode deixá-las escorrendo por um tempinho antes de descartá-las. Não é preciso lavá-las e nem retirar o conteúdo interno. Descarte em um lixo reciclável e suas cápsulas serão encaminhadas para uma cooperativa e após os processos sua cápsula ganha uma segunda vida e se tornará um novo objeto!</li></ul>",
    "informacoes_produto": {
      "Marca": "Nescafé Dolce Gusto",
      "Forma do produto": "Cápsula",
      "Sabor": "Avelã",
      "Descrição do teor de cafeína": "Com cafeína",
      "Nível de torragem": "Torra clara"
    },
    "affiliate_url": "https://www.amazon.com.br/Fita-Isolante-Mts-Preta-Unidade/dp/B077VTMHXQ/ref=zg_bs_g_hi_d_sccl_24/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-24",
    "title": "Adesivo de Silicone Acético Construção, Tekbond, 220.3400.2100, 256 Gramas/270 ML Transparente",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51UBaUNm-aL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 14.33,
    "price_original": 8.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1573,
    "coupon_code": null,
    "description": "<ul><li>O Silicone Acético Transparente Construcão é um adesivo selante tixotrópico monocomponente, baixo módulo, antifungo e de cura acética</li><li>Sua cura ocorre em temperatura ambiente e na exposição à umidade do ar.</li><li>É considerado um silicone de uso geral, muito utilizado na construção civil na vedação e selagem de pias e vasos sanitários, box em banheiros, portas e janelas.</li><li>Silicone de cura acética com alto grau de pureza.</li></ul>",
    "informacoes_produto": {
      "Marca": "TEK BOND",
      "Usos específicos do produto": "Construção",
      "Material": "Silicone",
      "Forma do produto": "Líquido",
      "Características especiais": "Cura em presença de umidade e antifungo"
    },
    "affiliate_url": "https://www.amazon.com.br/Silicone-Ac%C3%A9tico-Transparente-Tekbond-406715/dp/B076KR1Q3T/ref=zg_bs_g_hi_d_sccl_25/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-25",
    "title": "Tuut Ralo de Pia para Cozinha em Aço Inox Reforçado 11,5cm – Antientupimento e Fácil Limpeza",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51LsBFCIqjL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 7.5,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5598,
    "coupon_code": null,
    "description": "<ul><li>Excelente custo/benefício</li><li>Comum</li><li>Característica do produto: pequena</li><li>Voltagem: 1, 5V Conserto/ Troca: Troca</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA (necessita de baterias)",
      "Marca": "Panasonic",
      "Composição das células da bateria": "Alcalina",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "4.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Tuut-Linha-Inox-Tanque-Refor%C3%A7ado/dp/B089KV37SZ/ref=zg_bs_g_hi_d_sccl_26/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-26",
    "title": "Cabo de Rede Pluscable CAT.6 2.5M Branco Patch Cord - PC-ETH6U25WH",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41geUKI197L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 9.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5602,
    "coupon_code": null,
    "description": "<ul><li>Excelente custo/benefício</li><li>Comum</li><li>Característica do produto: pequena</li><li>Voltagem: 1, 5V Conserto/ Troca: Troca</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA (necessita de baterias)",
      "Marca": "Panasonic",
      "Composição das células da bateria": "Alcalina",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "4.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Cat-6-Patch-Plus-Cable-Branco/dp/B07SR1F7LS/ref=zg_bs_g_computers_d_sccl_27/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-27",
    "title": "Mouse Sem Fio Recarregável Wireless Bluetooth Optico Led Rgb Colorido Ergonômico Usb 2.4 Ghz Notebook Computador Pc Desktop Linha Premium | Óptico, Notebook Computador PC Desktop, Linha Premium, Wireless",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41X8XelsCqL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 17.4,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 17867,
    "coupon_code": null,
    "description": "<ul><li>Bamboo</li><li>Marrom</li><li>90 Dias</li></ul>",
    "informacoes_produto": {
      "Marca": "MOR",
      "Cor": "Palha",
      "Dimensões do produto": "35C x 25L x 1,5Espessura centímetros",
      "Material": "Madeira",
      "Adequação do controle por rádio": "Corte de legumes, verduras e carnes, Servir alimentos"
    },
    "affiliate_url": "https://www.amazon.com.br/Recarreg%C3%A1vel-Wireless-Bluetooth-Ergon%C3%B4mico-Computador/dp/B0CX4CYHVV/ref=zg_bs_g_computers_d_sccl_28/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-28",
    "title": "Adaptador de Tomada T Articulado – 10A e 20A – Até 250V – Bivolt 110V/220V – T - Plugue Benjamin Premium – Articulado e Seguro -Adaptador Flexível para Esconder Atrás do Móvel",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61ClaOPl1BL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 17.97,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 7417,
    "coupon_code": null,
    "description": "<ul><li>Caixa com 40 pilhas de zinco AAA Palito</li><li>Ideal para aparelhos que requerem descargas de energia rápidas e fortes.</li><li>Pilhas aprovadas pelo INMETRO: Testadas periodicamente por laboratórios credenciados pelo INMETRO, para garantir a qualidade e conformidade com a resolução Conama 401.</li><li>As pilhas Elgin têm ótima relação custo/benefício, você economiza e ainda conta com pilhas de alta qualidade.</li><li>Ecologicamente corretas: As Pilhas da Elgin têm 0% de Mercúrio e Cadmio em sua composição, colaborando para a preservação do meio ambiente.</li><li>Validade de 3 anos.</li><li>Voltagem 1.5V.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "40 AAA baterias necessárias. (inclusas)",
      "Marca": "Elgin",
      "Composição das células da bateria": "Zinco",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "40.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Adaptador-Tomada-Articulado-Benjamin-Adaptador/dp/B0FW81NYQ9/ref=zg_bs_g_hi_d_sccl_29/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-29",
    "title": "Duracell Pilhas Moeda CR2032 Pack 2 Unidades – Ideal para Placas Mãe e Controles Automotivos",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71TJ3Ud6gtL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 19.9,
    "price_original": 24.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 26590,
    "coupon_code": null,
    "description": "<ul><li>As pilhas moeda são usadas em chaveiros, controles remotos, chaves de carro, balanças, calculadoras, acessórios vestíveis (como óculos e relógios), entre outros..</li><li>As pilhas moeda são usadas em sensores, equipamentos médicos (medidores de glicemia, termômetros digitais), aparelhos desportivos (medidor de ritmo cardíaco, acessórios de ciclismo), entre outros.</li><li>A embalagem reforçada garante a segurança dos seus filhos: ela só pode ser aberta com uma tesoura.</li><li>A tecnologia de Duracell preserva a energia das pilhas que ainda não foram usadas, por até 10 anos.</li><li>As pilhas moeda Duracell 2032 são fabricadas com lítio de elevada pureza e têm energia de longa duração para diferentes equipamentos.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "2 Íon de lítio (necessita de baterias)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "255",
      "Adequação do controle por rádio": "Controles automotivos, Placas-mãe de computador, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Duracell-Pilhas-Unidades-Controles-Automotivos/dp/B08DQQC61G/ref=zg_bs_g_electronics_d_sccl_30/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-30",
    "title": "Bateria de Lítio Maxprint CR2032 3V – Alta Durabilidade – Blister com 5 Unidades – Para Relógios e Eletrônicos",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51+A+9GWZML._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 8.55,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1107,
    "coupon_code": null,
    "description": "<ul><li>Acesso em Alta: A Escadinha ajuda seu pequeno a alcançar a pia, vaso sanitário e banheira, tornando as tarefas diárias muito mais fáceis!</li><li>Segurança em Primeiro Lugar: Com borracha antiderrapante, sua criança fica segura durante o uso, permitindo que ela suba e desça sem preocupações!</li><li>Multiuso e Prática: Pode ser usada como um banquinho para ajudar mamães na hora do banho, oferecendo versatilidade e praticidade na rotina!</li><li>Compacta e Fácil de Guardar: Seu design inteligente permite que a escada seja armazenada facilmente, ideal para espaços pequenos!</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "27P x 37L x 17A centímetros",
      "Marca": "Clingo",
      "Material": "Polipropileno (PP)",
      "Cor": "Azul",
      "Características especiais": "Base larga para maior estabilidade e segurança., Degraus antiderrapante., Suporta até 80kg"
    },
    "affiliate_url": "https://www.amazon.com.br/Bateria-Lithium-Maxprint-3V-unidades/dp/B088CLY66K/ref=zg_bs_g_electronics_d_sccl_81/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-31",
    "title": "Mouse Pad, Azul, Maxprint, 603550",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51ensdrDjfL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 5.87,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2138,
    "coupon_code": null,
    "description": "<ul><li>DESIGN LEVE - Um terço mais leve do que as garrafas de aço inoxidável normais, graças à tecnologia AeroLight. Torna esta garrafa de água ideal para colocar na sua bolsa de trabalho, escola, faculdade ou academia.</li><li>DURÁVEL E ISOLADA - Fabricado em aço inoxidável 18/8 com isolamento a vácuo de parede dupla para um desempenho térmico duradouro. Tanto para bebidas quentes ou frias; mantém o seu café ou chá quente durante 8 horas, a sua água ou refrigerante gelados durante 12 horas e frescos durante 40 horas.</li><li>À PROVA DE VAZAMENTOS E SEGURA – Possui uma tampa com bloqueio e abertura para beber, garantindo transporte à prova de vazamentos, e a base estreita se encaixa na maioria dos porta-copos de carro.</li><li>MANUTENÇÃO FÁCIL - Pode ser lavada na máquina de lavar louça e não contém BPA.</li><li>STANLEY - Com uma rica história de 100 anos, a marca Stanley nos trouxe o isolamento a vácuo e revolucionou a maneira como consumimos bebidas. Do quente ao frio, os produtos Stanley são icônicos, duráveis e feitos para as aventuras modernas. Prepare-se para começar a sua.</li></ul>",
    "informacoes_produto": {
      "Marca": "Stanley",
      "Capacidade": "591 ml",
      "Cor": "Black",
      "Adequação do controle por rádio": "Café",
      "Características especiais": "Leve, À prova de vazamentos"
    },
    "affiliate_url": "https://www.amazon.com.br/Base-Padr%C3%A3o-Mouse-60355-0-Maxprint/dp/B078NVW1XT/ref=zg_bs_g_computers_d_sccl_82/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-32",
    "title": "3M, Feltro Sintético Adesivo para Móveis Leves Scotch, Quadrado, Marrom, Pequeno, 12 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81IGAoo7yhL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 6.99,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5348,
    "coupon_code": null,
    "description": "<ul><li>MULTIPLICADOR DE TOMADAS: Compacto, e em formato de cubo, o PowerCube transforma uma única tomada em 5 pontos de energia, que podem ser utilizadas simultaneamente para carregamento rápido de dispositivos eletrônicos.</li><li>TRAVA PARA CRIANÇAS: O sistema Child Lock garante proteção extra ao impedir a inserção acidental de objetos nas tomadas, liberando a entrada apenas quando os pinos são inseridos simultaneamente.</li><li>DESIGN PREMIADO: Com design premiado internacionalmente, sua estrutura única permite conectar todos os plugues ao mesmo tempo, sem bloqueios entre si. É ideal para uso em residências, escritórios e hotéis.</li><li>QUALIDADE PREMIUM: Fabricado em policarbonato antichamas, com conectores em cobre de alta pureza e certificação pelo Inmetro, obtenha segurança e eficiência em um produto bivolt de alto padrão.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Marca": "ELG",
      "Cor": "Verde e Branco",
      "Total de tomadas de energia": "5",
      "Tensão": "110 Volts, 220 Volts",
      "Características especiais": "Proteção de sobretensão"
    },
    "affiliate_url": "https://www.amazon.com.br/Feltro-Anti-Risco-Scotch-Marrom-Quadrado/dp/B07DCWV2TQ/ref=zg_bs_g_hi_d_sccl_83/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-34",
    "title": "PIX Suporte de TV Fixo Universal 10 a 100 Polegadas Compacto Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/617C5sIk3sL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 9.4,
    "price_original": 12.5,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1242,
    "coupon_code": null,
    "description": "<ul><li>Suporte Fixo Universal 10 a 100 Polegadas – Compatível com a maioria das TVs, ideal para otimizar espaço em salas, quartos e ambientes comerciais.</li><li>Capacidade de até 80 kg – Estrutura reforçada para suportar TVs grandes com estabilidade e segurança.</li><li>Instalação fácil – Acompanha kit completo de buchas e parafusos, garantindo praticidade na montagem.</li><li>Compatível com padrão VESA 75x75 a 800x400 mm – Ajuste simples a diferentes modelos e tamanhos de TVs sem complicações.</li><li>Garantia de 5 anos – Confiabilidade e durabilidade asseguradas para uso residencial e profissional.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "PIX",
      "Material": "Metal",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/PIX-Suporte-Universal-Polegadas-Compacto/dp/B0CM27NSBG/ref=zg_bs_g_electronics_d_sccl_35/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-35",
    "title": "PIX Suporte de TV Fixo Universal 10 a 100 Polegadas Compacto Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/617C5sIk3sL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 9.4,
    "price_original": 12.5,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1247,
    "coupon_code": null,
    "description": "<ul><li>Suporte Fixo Universal 10 a 100 Polegadas – Compatível com a maioria das TVs, ideal para otimizar espaço em salas, quartos e ambientes comerciais.</li><li>Capacidade de até 80 kg – Estrutura reforçada para suportar TVs grandes com estabilidade e segurança.</li><li>Instalação fácil – Acompanha kit completo de buchas e parafusos, garantindo praticidade na montagem.</li><li>Compatível com padrão VESA 75x75 a 800x400 mm – Ajuste simples a diferentes modelos e tamanhos de TVs sem complicações.</li><li>Garantia de 5 anos – Confiabilidade e durabilidade asseguradas para uso residencial e profissional.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "PIX",
      "Material": "Metal",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/PIX-Suporte-Universal-Polegadas-Compacto/dp/B0CM27NSBG/ref=zg_bs_g_electronics_d_sccl_36/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-36",
    "title": "Freezer-Roll Saco Para Alimentos 2 Litros Transparente Rolo Com 50 Sacos Cada",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71UZd3mywJL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 8.93,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 17730,
    "coupon_code": null,
    "description": "<ul><li>Verifique a voltagem antes de comprar o produto para certificar-se de que corresponde à da sua região</li><li>Tampa com trava de segurança</li><li>Base de contato separada</li><li>Com trava de segurança</li><li>Botão liga/desliga</li><li>Base separada</li><li>Luz LED operacional</li><li>Desliga automaticamente</li></ul>",
    "informacoes_produto": {
      "Marca": "Agratto",
      "Capacidade": "1,8 litros",
      "Material": "Aço inoxidável, Plástico",
      "Cor": "Preto/Inox",
      "Informações de embalagem": "RM"
    },
    "affiliate_url": "https://www.amazon.com.br/alimentos-Freezer-Roll-litros-transparente-sacos/dp/B0876T4473/ref=zg_bs_g_kitchen_d_sccl_87/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-37",
    "title": "Fita Veda Rosca",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51uArAYiVGL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 3.32,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 12789,
    "coupon_code": null,
    "description": "<ul><li>Jogo de Facas Tramontina Plenus com Lâminas em Aço Inox e Cabos de Polipropileno Preto 04 Peças</li><li>Número de modelo: 23498064</li><li>Nome de modelo: PLENUS</li><li>Tipo de produto: HOME</li></ul>",
    "informacoes_produto": {
      "Material da lâmina": "Aço inoxidável",
      "Marca": "Tramontina",
      "Cor": "Preto",
      "Material do cabo": "Polipropileno",
      "Borda da lâmina": "Plana"
    },
    "affiliate_url": "https://www.amazon.com.br/Fita-Veda-Rosca-Vonder-VDO2179/dp/B07JW7XYZX/ref=zg_bs_g_hi_d_sccl_88/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-38",
    "title": "EsfreBom - Saco para Lixo Rolo com 15 Sacos de 200 Litros, Cor Azul, Bettanin",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51vypsaVn1L._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 22.5,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 17722,
    "coupon_code": null,
    "description": "<ul><li>Verifique a voltagem antes de comprar o produto para certificar-se de que corresponde à da sua região</li><li>Tampa com trava de segurança</li><li>Base de contato separada</li><li>Com trava de segurança</li><li>Botão liga/desliga</li><li>Base separada</li><li>Luz LED operacional</li><li>Desliga automaticamente</li></ul>",
    "informacoes_produto": {
      "Marca": "Agratto",
      "Capacidade": "1,8 litros",
      "Material": "Aço inoxidável, Plástico",
      "Cor": "Preto/Inox",
      "Informações de embalagem": "RM"
    },
    "affiliate_url": "https://www.amazon.com.br/Saco-para-Lixo-Rolo-EsfreBom/dp/B07CTJ1JMP/ref=zg_bs_g_appliances_d_sccl_89/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-39",
    "title": "Vonder, Trena Curta De Aço 5 M X 19 Mm.",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71Y14RKTJBL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 14.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 20,
    "coupon_code": null,
    "description": "<ul><li>DESIGN CANELADO ELEGANTE: O acabamento canelado vertical confere sofisticação e um efeito visual refinado, valorizando a apresentação das bebidas.</li><li>JOGO COMPLETO COM 6 COPOS: Conjunto com 6 copos Sofia de 450ml cada, ideais para uso diário ou ocasiões especiais com estilo e praticidade.</li><li>VERSATILIDADE: Perfeitos para servir água, sucos, refrigerantes, drinks e coquetéis, combinando com diferentes estilos de mesa e ambientes.</li><li>VIDRO TRANSPARENTE DE ALTA QUALIDADE: Fabricados em vidro resistente e transparente, unindo beleza e durabilidade para o dia a dia.</li><li>ESTILO MODERNO: O design sofisticado combina perfeitamente com cozinhas modernas, mesas postas e ambientes que valorizam a elegância.</li></ul>",
    "informacoes_produto": {
      "Marca": "GATAO",
      "Material": "Vidro de borossilicato",
      "Cor": "Transparente",
      "Capacidade": "90 ml",
      "Características especiais": "Parede Dupla Isolante"
    },
    "affiliate_url": "https://www.amazon.com.br/Vonder-Trena-Curta-A%C3%A7o-Mm/dp/B0778XFVHN/ref=zg_bs_g_hi_d_sccl_40/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-40",
    "title": "Melitta Filtro de Papel 102 - 30 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81ZrxBKCaCL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 4.49,
    "price_original": 0.15,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 648,
    "coupon_code": null,
    "description": "<ul><li>Muita tecnologia para o seu café ficar sempre fresquinho e para você sentir mais a vida. Possuem microfuros e dupla costura/ disponível nos tamanhos 100 (200ml ou 4 xícaras ou 1 caneca - ideal para o preparo individual), 102 (800ml ou 16 xícaras) e 103 (1000ml ou 20 xícaras)</li><li>Tamanho 102 (ideal para preparar 800ml ou 16 xícaras de café)</li><li>Contem 30 filtros de papel</li><li>Único com microfuros</li></ul>",
    "informacoes_produto": {
      "Material": "Papel",
      "Marca": "Melitta",
      "Forma": "Cone",
      "Número de peças": "1",
      "Dispositivos compatíveis": "Cafeteira"
    },
    "affiliate_url": "https://www.amazon.com.br/Filtro-para-Caf%C3%A9-102-Melitta/dp/B078XNNYG6/ref=zg_bs_g_kitchen_d_sccl_41/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-41",
    "title": "Melitta Filtro de Papel 102 - 30 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81ZrxBKCaCL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 4.49,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 960,
    "coupon_code": null,
    "description": "<ul><li>🌍 Adaptação Total em +150 Países Viaje com liberdade total! Com suporte para os plugues dos tipos A, B, C, D, E, F, G e I, este adaptador universal é compatível com mais de 150 países — incluindo Estados Unidos, Reino Unido, Japão, Austrália e toda a União Europeia. Ideal para quem viaja a trabalho ou lazer e não quer correr riscos com conectividade.</li><li>⚡ Tecnologia Bivolt Inteligente Compatível com tensões de 110V a 220V, o adaptador ajusta automaticamente a voltagem local, protegendo seus dispositivos contra picos de energia. Sem necessidade de ajustes manuais, sem riscos de queima — conecte e relaxe.</li><li>🧳 Compacto e Portátil – Cabe em Qualquer Espaço Leve, dobrável e fácil de guardar. Ideal para malas de mão, mochilas ou estojos de eletrônicos. O design inteligente com plugues retráteis evita volume desnecessário e é perfeito para o dia a dia ou viagens longas.</li><li>🛡️ Segurança de Ponta: Proteção Total Contra Sobrecarga Equipado com sistemas de proteção contra curto-circuito, sobrecarga e superaquecimento, garantindo a segurança dos seus dispositivos e tranquilidade durante o uso, em qualquer lugar do mundo.</li><li>💎 Durabilidade Profissional com Acabamento Premium Fabricado com materiais de alta qualidade, resistente ao desgaste diário e a impactos leves. Perfeito para uso recorrente por viajantes frequentes, empresários e famílias.</li><li>💎 Pinos retrateis</li><li>💎 LED indicador de energia.</li></ul>",
    "informacoes_produto": {
      "Marca": "Genérico",
      "Cor": "branco",
      "Tensão de saída": "220 Volts",
      "Tipo de plugue": "Tipo C, Tipo E, Tipo F",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Filtro-para-Caf%C3%A9-102-Melitta/dp/B078XNNYG6/ref=zg_bs_g_kitchen_d_sccl_42/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-42",
    "title": "EDA Abraçadeira De Nylon 2 5 X 150 Mm Com 100 Peças Branca Eda",
    "image": "https://images-na.ssl-images-amazon.com/images/I/710DkfnfzyL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 3.05,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2023,
    "coupon_code": null,
    "description": "<ul><li>Abraçadeiras de nylon</li><li>Pacote com 100 peças</li><li>Medidas: 2, 5 x 150 milímetros</li><li>Cor branca</li></ul>",
    "informacoes_produto": {
      "Material": "Nylon",
      "Cor": "branca",
      "Marca": "EDA",
      "Comprimento do produto": "2 Centímetros",
      "Estilo": "100 peças"
    },
    "affiliate_url": "https://www.amazon.com.br/Abra%C3%A7adeira-Nylon-150-Pe%C3%A7as-Branca/dp/B07QXL7VZL/ref=zg_bs_g_hi_d_sccl_93/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-43",
    "title": "Balança de Cozinha Inox Digital para Alimentos Dieta Fitness Alta Precisão Resistente a Água Com Base Antiderrapante e Visor de Alta Definição Pesagem de 1g até 10kg Premium",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61pmri0rM4L._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 28.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 9918,
    "coupon_code": null,
    "description": "<ul><li>Conjunto formado por três bowls de aço inoxidável com tampa plástica para preparar servir e conservar alimentos na geladeira.</li><li>Com 3 tamanhos, atendem as mais variadas necessidades, como temperar carnes, fazer massas, servir saladas e preparar molhos.</li><li>Feitos de aço inoxidável, são mais duráveis e o acabamento polido facilita a limpeza. Perfeitos para preparar e servir, além de decorar a mesa.</li><li>Este produto pode ser usado no refrigerador e lavado na lava-louças.</li><li>Informações técnicas: Ø 22cm | 2,6 L Ø 19,5cm | 2 L Ø 17,5cm | 1,4 L</li></ul>",
    "informacoes_produto": {
      "Material da tigela": "Aço inoxidável",
      "Número de peças": "3",
      "Marca": "Electrolux",
      "Cor": "Inox",
      "Características especiais": "Durável, Seguro para congelador"
    },
    "affiliate_url": "https://www.amazon.com.br/Alimentos-Precis%C3%A3o-Resistente-Antiderrapante-Defini%C3%A7%C3%A3o/dp/B0FNXCLLDV/ref=zg_bs_g_kitchen_d_sccl_94/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-46",
    "title": "MD9 - CONECTOR RJ-45 EMB.C/ 10 UNID. 8 VIAS",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51wu1DVT3NL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Computadores e Informática",
    "price_current": 3.85,
    "price_original": 4.64,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 259,
    "coupon_code": null,
    "description": "<ul><li>Conector RJ-45 para montagem de cabos de rede com suporte a alta velocidade, compatível com computadores pessoais.</li><li>Design transparente com 8 vias, padrão RJ-45, permitindo visualização da fiação durante a montagem dos cabos de rede.</li><li>Embalagem com 10 unidades de conectores RJ-45, ideal para montagem de múltiplos cabos de rede de forma prática e econômica.</li></ul>",
    "informacoes_produto": {
      "Marca": "MD9",
      "Tipo de conector": "RJ45",
      "Tipo de cabo": "Ethernet",
      "Dispositivos compatíveis": "Computador pessoal, Roteador, Servidor, Switch de rede",
      "Características especiais": "Alta velocidade"
    },
    "affiliate_url": "https://www.amazon.com.br/MD9-CONECTOR-RJ-45-EMB-C-UNID/dp/B076HQVSXZ/ref=zg_bs_g_computers_d_sccl_47/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-47",
    "title": "3M, Feltro Sintético Adesivo para Móveis Leves Scotch, Redondo, Marrom, Pequeno, 12 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81CV0pfB9PL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 6.66,
    "price_original": 36.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1974,
    "coupon_code": null,
    "description": "<ul><li>PROTEJA SEU PISO. O Protetor de Feltro Scotch 3M é a solução ideal para proteger pisos de madeira, vinílicos, cerâmicos ou laminados de forma discreta e eficiente.</li><li>ALTA QUALIDADE E ADERÊNCIA. Fabricado com feltro sintético de alta resistência, este protetor garante durabilidade e proteção superior, além de um adesivo de alta fixação para longa duração.</li><li>FÁCIL DE USAR. Com formato redondo e tamanho pequeno (2,5 x 2,5 cm), é perfeito para móveis leves como cadeiras, mesas, pufes e banquetas.</li><li>O QUE ESTÁ INCLUÍDO. Este pacote contém 12 feltros protetores autocolantes, na cor marrom, prontos para serem aplicados nos pés de seus móveis.</li><li>CIÊNCIA APLICADA À VIDA. A 3M é uma multinacional que, por meio de suas marcas, oferece soluções sustentáveis que otimizam o tempo e a energia das pessoas, melhorando suas vidas diariamente.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Anti-Risco-Redondo-Scotch-HB004262687-Pequeno/dp/B07CLH9Y6X/ref=zg_bs_g_hi_d_sccl_48/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-48",
    "title": "Livro Dedoche - Abração: Abração de Gato",
    "image": "https://images-na.ssl-images-amazon.com/images/I/616agTn+BeL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 15.0,
    "price_original": 29.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 726,
    "coupon_code": null,
    "description": "<ul><li>Livro interativo</li><li>Brincadeira com a criança</li><li>Braços macios do gato</li></ul>",
    "informacoes_produto": {
      "Marca": "Todolivro",
      "Tecnologia de conectividade": "Sem fio",
      "Características especiais": "Visão noturna",
      "Ambiente interno/externo": "Área externa",
      "Resolução de captura de vídeo": "1080p"
    },
    "affiliate_url": "https://www.amazon.com.br/Livro-Dedoche-Abra%C3%A7%C3%A3o-Gato/dp/6556170666/ref=zg_bs_g_hi_d_sccl_99/146-0500837-0878747?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0918FHY6P",
    "title": "L'Oréal Professionnel Óleo 10 em 1 Absolut Repair | Multi-benefícios para cabelos secos e danificados | Repara e Promove Brilho | Com Gold Quinoa e Proteínas",
    "image": "https://m.media-amazon.com/images/I/61wfwHNv-NL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 123.39,
    "price_original": 247.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 22703,
    "coupon_code": null,
    "description": "<ul><li>Óleo de tratamento leave-in multibenefícios 10 em 1, que oferece nutrição, reparação instantânea e brilho para os fios</li><li>Sua fórmula profissional é enriquecida com Proteína do Trigo, garantindo uma restauração profunda e cabelos mais resistentes</li><li>Proporciona maciez e maleabilidade com um toque leve, sem pesar, facilitando o cuidado diário</li><li>Oferece proteção térmica e contra agressões externas, mantendo os cabelos saudáveis e protegidos no dia a dia</li><li>Repara a fibra capilar danificada, devolvendo a suavidade e o brilho para um resultado de salão instantâneo em casa</li></ul>",
    "informacoes_produto": {
      "Tipo de cabelo": "Fino",
      "Tipo de material livre": "Sem conservantes",
      "Aroma": "Sem perfume",
      "Volume líquido": "1 Onças líquidas"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Multi-benef%C3%ADcios-danificados-Prote%C3%ADnas/dp/B0918FHY6P?ref=dlx_deals_dg_dcl_B0918FHY6P_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DYVNRG3B",
    "title": "Celular Samsung Galaxy A36 5G 128GB, 6GB RAM, Câmera 50MP, IP67, Super AMOLED 6.7\", Recursos AI, Branco",
    "image": "https://m.media-amazon.com/images/I/613Vrz+GcaL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1449.0,
    "price_original": 2699.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2479,
    "coupon_code": null,
    "description": "<ul><li>Feito para Durar: até 6 atualizações de Android e Segurança</li><li>Tela imersiva de 6.7\" Super AMOLED com Vision Booster</li><li>Resistente à água e poeira com IP67</li><li>Câmera com recursos de AI e Nightography / Circule para Pesquisar no Google</li><li>Bateria de 5000 mAh e carregamento rápido de até 45W</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Sistema operacional": "Android 15.0",
      "Tamanho instalado da memória RAM": "6 GB",
      "Modelo da CPU": "A-Series",
      "Velocidade da CPU": "2 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Celular-Samsung-Galaxy-C%C3%A2mera-Recursos/dp/B0DYVNRG3B?ref=dlx_deals_dg_dcl_B0DYVNRG3B_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": true
  },
  {
    "asin": "B0H4J13B2M",
    "title": "Notebook Gamer Lenovo Loq, I5-12450hx, 16gb Ddr5, 1tb Ssd, Rtx 4050 6gb, 15.6\" Fhd, W11, Cinza - 83me0001br",
    "image": "https://m.media-amazon.com/images/I/51lylzSiLML._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 6099.99,
    "price_original": 6665.56,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Notebook Gamer Lenovo LOQ Intel i5 16GB RAM 1TB SSD RTX 4050</li><li>Placa de vídeo dedicada RTX 4050 6GB</li><li>Processador Intel Core i5-12450HX</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "1 TB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Windows 11",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "31 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Gamer-Lenovo-I5-12450hx-Cinza/dp/B0H4J13B2M?ref=dlx_deals_dg_dcl_B0H4J13B2M_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": true
  },
  {
    "asin": "B0GT6LW2VN",
    "title": "JBL, Caixa de Som, PartyBox Encore Essential 2 Mic, Show de Luzes, Bluetooth, Portátil, Resistente a Respingos, Bateria de até 15h, Som JBL Pro Sound, AI Sound Boost, 100 W RMS",
    "image": "https://m.media-amazon.com/images/I/61Z9gLQHMIL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1939.0,
    "price_original": 2699.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 64,
    "coupon_code": null,
    "description": "<ul><li>SOM POTENTE COM AI SOUND BOOST. O JBL Pro Sound ganha ainda mais potência com o AI Sound Boost, oferecendo agudos nítidos e graves impactantes, mesmo em alto volume e ambientes amplos.</li><li>SHOW DE LUZES NO RITMO DA MÚSICA. Os efeitos de luzes dinâmicas criam o clima ideal para qualquer festa, com padrões vibrantes e estroboscópicos que seguem o ritmo da sua playlist do começo ao fim.</li><li>TECNOLOGIA Auracast. É possível emparelhar com outro JBL PartyBox Encore Essential 2 ou conectar várias caixas via JBL Auracast para ampliar sua experiência sonora.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Dimensões do item C x L x A": "29 x 33 x 28 centímetros",
      "Tecnologia de conectividade": "Bluetooth",
      "Dispositivos compatíveis": "Microfone, Outro JBL PartyBox Encore Essential 2",
      "Tipo de montagem": "Portátil"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-Essential-Bluetooth-Resistente-Respingos/dp/B0GT6LW2VN?ref=dlx_deals_dg_dcl_B0GT6LW2VN_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": true
  },
  {
    "asin": "B09GSQMVJS",
    "title": "L'Oréal Professionnel Inforcer Shampoo Fortificante Antiqueda por Quebra, Crescimento Saudável Para Cabelos Frágeis e Quebradiços Com Biotina e Vitamina B6, 300ml",
    "image": "https://m.media-amazon.com/images/I/51TvgvfNA9L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 67.4,
    "price_original": 116.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7277,
    "coupon_code": null,
    "description": "<ul><li>Um tratamento em shampoo que limpa, fortalece e proporciona uma ação anti-quebra instantânea nos fios.</li><li>Enriquecido com Biotina e Vitamina B6, que estimulam o crescimento saudável e o metabolismo de proteínas.</li><li>Leva nutrientes à fibra capilar, promovendo força instantânea e prevenindo o ressecamento e a quebra.</li><li>Com o uso contínuo, os cabelos se tornam mais resistentes, com menos queda e com um crescimento visível.</li><li>Conquiste cabelos suplementados com força, nutridos, resistentes e com o crescimento saudável que você deseja.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Líquido",
      "Tipo de cabelo": "Todos os tipos de cabelos",
      "Aroma": "Sem perfume",
      "Faixa etária (descrição)": "Adulto"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Fortificante-Anti-Quebra-Quebradi%C3%A7os/dp/B09GSQMVJS?ref=dlx_deals_dg_dcl_B09GSQMVJS_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B07Y3B33KG",
    "title": "Finish Powerball Detergente para Lava Louças em tabletes Embalagem Econômica com 91 tabletes",
    "image": "https://m.media-amazon.com/images/I/61Nf8UQrPOL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 127.15,
    "price_original": 277.78,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 6525,
    "coupon_code": null,
    "description": "<ul><li>Finish Powerball Tabletes é o seu detergente para lava louças que oferece limpeza poderosa e brilho perfeito em um único tablete.</li><li>Louça perfeitamente limpa de primeira, sem necessidade de pré-lavagem, gerando economia de água.</li><li>Prático e pronto para o uso, já vem na medida certa. Invista em qualidade de vida!</li><li>Finish é líder mundial em detergente para máquina lava louças. Recomendado pelos principais fabricantes de lava louças do mundo como Brastemp e Electrolux.</li><li>Possui agentes secantes na fórmula. Sua fórmula contém ingredientes que promovem o cuidado e proteção das louças.</li></ul>",
    "informacoes_produto": {
      "Marca": "Finish",
      "Forma do produto": "Tablet",
      "Aroma": "Sem perfume",
      "Característica do material": "Sem perfume",
      "Número de itens": "91"
    },
    "affiliate_url": "https://www.amazon.com.br/Detergentes-Powerball-Embalagem-Econ%C3%B4mica-Finish/dp/B07Y3B33KG?ref=dlx_deals_dg_dcl_B07Y3B33KG_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": true
  },
  {
    "asin": "B000WLN7AM",
    "title": "Whisky Bourbon Maker's Mark 750ml",
    "image": "https://m.media-amazon.com/images/I/7199P9zzMGL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 119.9,
    "price_original": 145.33,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3373,
    "coupon_code": null,
    "description": "<ul><li>Com coloração âmbar, laranja-amarelada, o bourbon tornou-se um dos destilados mais apreciados no mundo.</li><li>Diferentemente da composição do whisky tradicional, o Maker’s Mark não possui centeio na sua formulação, e sim, trigo doce e vermelho de inverno, milho e cevada.</li><li>O sucesso é fruto de um processo produtivo minucioso, que segue à risca os padrões de qualidade.</li><li>A produção é feita em baixa escala, em lotes individuais que não ultrapassam 19 barris por lote.</li><li>O Maker’s Mark é envelhecido por cerca de seis anos, depois de engarrafado é então selado em uma garrafa de forma única e selada com a cera vermelha na rolha.</li></ul>",
    "informacoes_produto": {
      "Marca": "Maker's Mark",
      "Tipo de álcool": "Bourbon",
      "Sabor": "Chocolate",
      "Contagem de unidades": "750.0 Mililitro",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Whiskey-MakerS-Mark-Makers-Sabor/dp/B000WLN7AM?ref=dlx_deals_dg_dcl_B000WLN7AM_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D216Q2NR",
    "title": "Ar Condicionado Split Hi Wall R32 LG Dual Inverter Voice +AI 18000 BTU/h Frio S3-Q18KL31B – 220 Volts",
    "image": "https://m.media-amazon.com/images/I/41LEG77cCPL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 3249.0,
    "price_original": 3499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 218,
    "coupon_code": null,
    "description": "<ul><li>Ar-Condicionado Split LG Dual Inverter Voice R-32 +AI R-32 Os equipamentos de climatização estão ficando cada vez mais tecnológicos, facilitando o seu uso e a sua rotina. O ar-condicionado split LG dual inverter voice é ideal para quem quer refrescar os ambientes menores com mais conforto e bem-estar. O aparelho conta com Wi-fi integrado e pronto para usar, além de possuir gás ecológico R-32.</li></ul>",
    "informacoes_produto": {
      "Marca": "LG",
      "Capacidade": "63,4 quilogramas",
      "Energia de resfriamento": "18000 BTUs",
      "Características especiais": "Inverter",
      "Dimensões do produto": "0,3P x 3,78L x 9,05A Metros"
    },
    "affiliate_url": "https://www.amazon.com.br/Condicionado-Split-LG-Inverter-S3-Q18KL31B/dp/B0D216Q2NR?ref=dlx_deals_dg_dcl_B0D216Q2NR_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": true
  },
  {
    "asin": "B07FPW95CM",
    "title": "Jameson - Whiskey Irlandês, 750 ml",
    "image": "https://m.media-amazon.com/images/I/51syfbaTceL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 69.08,
    "price_original": 130.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7094,
    "coupon_code": null,
    "description": "<ul><li>Sabor suave e equilibrado com toque adocicado</li><li>Destilado triplo de alta qualidade</li><li>Ideal para drinks ou puro</li><li>Garrafa elegante e tradicional</li><li>Whiskey irlandês reconhecido mundialmente</li></ul>",
    "informacoes_produto": {
      "Marca": "Jameson",
      "Tipo de álcool": "Blended whiskey",
      "Sabor": "Whisky",
      "Número de itens": "1",
      "Teor alcoólico": "15 %"
    },
    "affiliate_url": "https://www.amazon.com.br/Jameson-Whisky-750ml/dp/B07FPW95CM?ref=dlx_deals_dg_dcl_B07FPW95CM_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DKVJ1HWB",
    "title": "Lola Cosmetics Kit Cronograma Capilar Be(m) Dita Ghee - 3 Produtos",
    "image": "https://m.media-amazon.com/images/I/71K-GAoX50L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 38.8,
    "price_original": 69.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 6337,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/FEIRA-CRONOLOLA-Cronograma-Capilar-Produtos/dp/B0DKVJ1HWB?ref=dlx_deals_dg_dcl_B0DKVJ1HWB_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GHP4NL1J",
    "title": "Kit Rapunzel (Shampoo + Tônico + Milk Spray) - Lola From Rio",
    "image": "https://m.media-amazon.com/images/I/41OcWO275YL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 58.52,
    "price_original": 119.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 427,
    "coupon_code": null,
    "description": "<ul><li>Estimula o crescimento capilar, reduz a queda dos fios e nutre o couro cabeludo com fórmula vegana, cruelty-free e livre de sulfatos e silicones.</li><li>Kit composto por Shampoo, Tônico e Milk Spray com embalagens multicoloridas, da linha Rapunzel da marca Lola From Rio.</li><li>Fórmula leve e não oleosa indicada para uso diário, sem pesar os fios, mantendo a hidratação e o equilíbrio natural do couro cabeludo.</li></ul>",
    "informacoes_produto": {
      "Tipo de material livre": "Livre de sulfato",
      "Forma do produto": "Líquido",
      "Marca": "Lola",
      "Tipo de cabelo": "Cacheado, Danificado, Normal, Opaco, Todos"
    },
    "affiliate_url": "https://www.amazon.com.br/Rapunzel-Shampoo-T%C3%B4nico-Milk-Spray/dp/B0GHP4NL1J?ref=dlx_deals_dg_dcl_B0GHP4NL1J_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0C9RVFRZD",
    "title": "Duracell Pilhas Alcalinas AA Pequena Pack 24 Unidades – Dura até 10x Mais – Ideal para Controle de Videogame e Brinquedos",
    "image": "https://m.media-amazon.com/images/I/81k5RxCXI5L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 99.65,
    "price_original": 124.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 33273,
    "coupon_code": null,
    "description": "<ul><li>Pilha Duracell Alcalina AA que fornece mais duração e potência para os aparelhos</li><li>Dura mais, muito mais</li><li>Longa duração: As pilhas alcalinas AA Duracell duram mais que as pilhas comuns de zinco-carbono, oferecendo energia confiável e de alto desempenho</li><li>As pilhas Duracell podem manter sua capacidade energética por até 10 anos, mesmo sem uso, garantindo energia disponível quando você precisar</li><li>Projetadas para oferecer o melhor desempenho em dispositivos de uso diário, como brinquedos, lanternas, controles remotos e teclados</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "24 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "200",
      "Adequação do controle por rádio": "Brinquedos, Controle de videogame, Controle remoto"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilha-AA-Pequena-24-Unidades/dp/B0C9RVFRZD?ref=dlx_deals_dg_dcl_B0C9RVFRZD_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FVB5G3V7",
    "title": "Whisky Escocês Laphroaig Quarter Cask 700ml",
    "image": "https://m.media-amazon.com/images/I/71PgVsX00EL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 379.9,
    "price_original": 475.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 29,
    "coupon_code": null,
    "description": "<ul><li>Cor: Ouro cintilante.</li><li>Aroma: Turfa fumegante com aromas de côco e banana.</li><li>Acabamento: Longo e ressecante com fumaça e especiarias.</li><li>Sabor: Profundo, complexo e defumado com uma doçura suave.</li></ul>",
    "informacoes_produto": {
      "Marca": "Laphroaig",
      "Tipo de álcool": "Uísque de malte único",
      "Sabor": "Caramelo",
      "Número de itens": "1",
      "Teor alcoólico": "48 %"
    },
    "affiliate_url": "https://www.amazon.com.br/Whisky-Escoc%C3%AAs-Laphroaig-Quarter-700ml/dp/B0FVB5G3V7?ref=dlx_deals_dg_dcl_B0FVB5G3V7_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "B0F3QPRN9M",
    "title": "Ar Condicionado Split Hi Wall TCL T-Pro 2.0 Inverter 12.000 Btus Frio 220v R-32",
    "image": "https://m.media-amazon.com/images/I/51OmHUb71RL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1890.23,
    "price_original": 3370.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 301,
    "coupon_code": null,
    "description": "<ul><li>Tecnoligia inveryer</li><li>Conectividade via app TCL Home</li><li>Funcionamento silencioso e uma economia significativa de energia</li><li>Equipado com filtros avançados, o aparelho remove poeira, ácaros e outras impurezas, melhorando a qualidade do ar e promovendo mais saúde para você e sua família.</li></ul>",
    "informacoes_produto": {
      "Marca": "TCL",
      "Capacidade": "1 tons",
      "Características especiais": "Aplicação do ar;condicionado: Resfriamento, Requer Unidade Externa: Sim",
      "Dimensões do produto": "79,6P x 27L x 21,3A centímetros",
      "Cor": "Branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Condicionado-Split-TCL-Inverter-12-000/dp/B0F3QPRN9M?ref=dlx_deals_dg_dcl_B0F3QPRN9M_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": true
  },
  {
    "asin": "index-2",
    "title": "Docol Sifão Extensível Universal 72cm - Cod.Novo: 90007965026 Cod.Antigo: 00796526",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41F+jsxUxLL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Ferramentas e Materiais de Construção",
    "price_current": 14.27,
    "price_original": 35.04,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1045,
    "coupon_code": null,
    "description": "<ul><li>Livre de odores indesejados: equipado com o sistema antiodor, o produto impede o retorno de gases existentes nas tubulações de esgoto.</li><li>Dispensa o uso de fita vedarosca: o produto é equipado com anéis para vedação que dispensam o uso de fita veda-rosca.</li><li>Compatibilidade com válvulas de saída d’água para cozinha, lavatório e tanque.</li><li>Trava: dispositivo que garante os 5cm de fecho hídrico (exigência da norma).</li><li>Comprimento de 72cm: maior do que a grande maioria dos sifões do mercado, que possibilita instalações com facilidade e ambientes de difícil acesso. Compatibilidade com tubulações de 40 e 50mm, tanto em conexões como diretamente em tubos.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Sif%C3%A3o-Universal-Extens%C3%ADvel-Docol-72/dp/B08KJN19FM/ref=zg_bs_g_hi_d_sccl_3/141-0633385-3597149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  },
  {
    "asin": "index-3",
    "title": "Oikos - Espatula de Silicone Reta Vermelha Pequena",
    "image": "https://images-na.ssl-images-amazon.com/images/I/31dueR4WZRL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 14.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 12343,
    "coupon_code": null,
    "description": "<ul><li>Utensílios de silicone para o preparo de alimentos: passam por qualquer superfície sem deixar nenhum arranhão.</li><li>Silicone duplo: duas camadas de silicone que o deixam muito mais resistente sem perder a suavidade.</li><li>Superfície lisa: não retém cheiro nem prolifera bactérias.</li><li>Livre de BPA: não libera substâncias tóxicas na comida.</li><li>Essa é a espátula de silicone reta pequena da OIKOS.</li></ul>",
    "informacoes_produto": {
      "Material": "Metal, Silicone",
      "Cor": "Vermelho",
      "Marca": "OIKOS",
      "Tamanho": "Pequena",
      "Dimensões do produto": "20,7C x 4,2L centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Esp%C3%A1tula-Silicone-Reta-Pequena-OIKOS/dp/B085M4Z3N4/ref=zg_bs_g_kitchen_d_sccl_4/141-0633385-3597149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T16:16:11.000Z",
    "spotlight": false
  }
];
